### ISSUE TITLE
fftool version

### ISSUE THREAD

**Issue by kateryna-goloviznina** [paduagroup/pol_openmm#36]
Hello Agilio,
I see that you have modified the structure of the field file. 
It could be nice to mention somewhere in the manual that polxml and scaleLJsml scripts should be used with a **new version** of fftool (no older than 02/24, for example).
I already have some users running into problems because of this.
Thank you,
Katya

**Comment by agiliopadua** [comment]
Ok, done! Jut updated the README. Thx

**Comment by kateryna-goloviznina** [comment]
Thanks!
